### ISSUE TITLE
Port extension to Chrome

### ISSUE THREAD

**Issue by itsmegrave** [SamuelGrave/mussum-ipsum-addon#2]

**Comment by ghost** [comment]
does it mean to upload mussum-ipsum-addon to Chrome web store - extension?

**Comment by itsmegrave** [comment]
@x1yy not exactly.
On chrome this extension have some strange behaviours.
So this issue is basically to fix it, and make it works like it works on firefox.

**Comment by Ondkloss** [comment]
Can't quite see that there are any issues to work on here? Looks like it works fine on Chrome for me. Close issue?
