### ISSUE TITLE
Add copy to clipboard functionality

### ISSUE THREAD

**Issue by itsmegrave** [SamuelGrave/mussum-ipsum-addon#3]

**Comment by hacksdump** [comment]
I'd like to work upon this.

**Comment by kwaimind** [comment]
Didn't see this task get assigned so I pushed a suggested version of how this would work. Let me know if that's what you're looking for. 

You might also want to look into how your paragraphs are made, as they don't start on a new line break.

**Comment by itsmegrave** [comment]
@kwaimind I'll create a issue about the paragraphs, ok?
