### ISSUE TITLE
Create a UI for extension

### ISSUE THREAD

**Issue by itsmegrave** [SamuelGrave/mussum-ipsum-addon#4]

**Comment by PaulJasiul** [comment]
I will do it.

**Comment by ksandhu16** [comment]
more details please?

**Comment by itsmegrave** [comment]
@ksandhu16 I don't have any spec for it.
I'm accepting any improvements on addon layout.

**Comment by ksandhu16** [comment]
ok I am working on this !

**Comment by itsmegrave** [comment]
thanks for the help, @ksandhu16 !
